version: '3'
services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    environment:
      - API_HOST=api
      - API_PORT=4000
  api:
    build: ./api
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=db
  emailer:
    build:
      context: ./
      dockerfile: Dockerfile.emailer
    environment:
      - APP_ENV=production
      - API_HOST=api
  db:
    image: mongo
  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
