version: '3'
services:
  ui:
    image: ryanoglesby08/eod-machine:ui-1.0.0
    ports:
      - '80:3000'
    environment:
      - API_HOST=api
      - API_PORT=4000
  api:
    image: ryanoglesby08/eod-machine:api-1.0.0
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=db
  emailer:
    image: ryanoglesby08/eod-machine:emailer-1.0.0
    environment:
      - API_HOST=api
      - API_PORT=4000
  db:
    image: mongo
