version: '3'
services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile.ui
    ports:
     - "3000:3000"
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
     - "4000:4000"
  emailer:
    build:
      context: ./
      dockerfile: Dockerfile.emailer
    environment:
      - APP_ENV=production
  db:
    image: mongo
  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
